/**
 * battleReducerActions.js
 *
 * 전투 액션 타입 정의
 * battleReducer.js에서 분리됨
 */

export const ACTIONS = {
  // === 플레이어/적 상태 ===
  SET_PLAYER: 'SET_PLAYER',
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  SET_ENEMY: 'SET_ENEMY',
  UPDATE_ENEMY: 'UPDATE_ENEMY',
  SET_ENEMY_INDEX: 'SET_ENEMY_INDEX',
  SET_SELECTED_TARGET_UNIT: 'SET_SELECTED_TARGET_UNIT',
  UPDATE_ENEMY_UNIT: 'UPDATE_ENEMY_UNIT',
  SET_ENEMY_UNITS: 'SET_ENEMY_UNITS',

  // === 페이즈 ===
  SET_PHASE: 'SET_PHASE',

  // === 카드 관리 ===
  SET_HAND: 'SET_HAND',
  SET_SELECTED: 'SET_SELECTED',
  ADD_SELECTED: 'ADD_SELECTED',
  REMOVE_SELECTED: 'REMOVE_SELECTED',
  SET_CAN_REDRAW: 'SET_CAN_REDRAW',
  SET_SORT_TYPE: 'SET_SORT_TYPE',
  SET_VANISHED_CARDS: 'SET_VANISHED_CARDS',
  ADD_VANISHED_CARD: 'ADD_VANISHED_CARD',
  SET_USED_CARD_INDICES: 'SET_USED_CARD_INDICES',
  SET_DISAPPEARING_CARDS: 'SET_DISAPPEARING_CARDS',
  SET_HIDDEN_CARDS: 'SET_HIDDEN_CARDS',
  SET_DISABLED_CARD_INDICES: 'SET_DISABLED_CARD_INDICES',
  SET_CARD_USAGE_COUNT: 'SET_CARD_USAGE_COUNT',
  INCREMENT_CARD_USAGE: 'INCREMENT_CARD_USAGE',

  // === 덱/무덤 시스템 ===
  SET_DECK: 'SET_DECK',
  SET_DISCARD_PILE: 'SET_DISCARD_PILE',
  ADD_TO_DISCARD: 'ADD_TO_DISCARD',
  DRAW_FROM_DECK: 'DRAW_FROM_DECK',
  SHUFFLE_DISCARD_INTO_DECK: 'SHUFFLE_DISCARD_INTO_DECK',

  // === 적 계획 ===
  SET_ENEMY_PLAN: 'SET_ENEMY_PLAN',

  // === 실행 큐 ===
  SET_FIXED_ORDER: 'SET_FIXED_ORDER',
  SET_QUEUE: 'SET_QUEUE',
  SET_Q_INDEX: 'SET_Q_INDEX',
  INCREMENT_Q_INDEX: 'INCREMENT_Q_INDEX',

  // === 로그 & 이벤트 ===
  ADD_LOG: 'ADD_LOG',
  SET_LOG: 'SET_LOG',
  SET_ACTION_EVENTS: 'SET_ACTION_EVENTS',

  // === 턴 ===
  SET_TURN_NUMBER: 'SET_TURN_NUMBER',
  INCREMENT_TURN: 'INCREMENT_TURN',

  // === 에테르 ===
  SET_TURN_ETHER_ACCUMULATED: 'SET_TURN_ETHER_ACCUMULATED',
  SET_ENEMY_TURN_ETHER_ACCUMULATED: 'SET_ENEMY_TURN_ETHER_ACCUMULATED',
  SET_NET_ETHER_DELTA: 'SET_NET_ETHER_DELTA',
  SET_ETHER_ANIMATION_PTS: 'SET_ETHER_ANIMATION_PTS',
  SET_ETHER_FINAL_VALUE: 'SET_ETHER_FINAL_VALUE',
  SET_ENEMY_ETHER_FINAL_VALUE: 'SET_ENEMY_ETHER_FINAL_VALUE',
  SET_ETHER_CALC_PHASE: 'SET_ETHER_CALC_PHASE',
  SET_ENEMY_ETHER_CALC_PHASE: 'SET_ENEMY_ETHER_CALC_PHASE',
  SET_CURRENT_DEFLATION: 'SET_CURRENT_DEFLATION',
  SET_ENEMY_CURRENT_DEFLATION: 'SET_ENEMY_CURRENT_DEFLATION',
  SET_ETHER_PULSE: 'SET_ETHER_PULSE',
  SET_PLAYER_TRANSFER_PULSE: 'SET_PLAYER_TRANSFER_PULSE',
  SET_ENEMY_TRANSFER_PULSE: 'SET_ENEMY_TRANSFER_PULSE',

  // === 기원 ===
  SET_WILL_OVERDRIVE: 'SET_WILL_OVERDRIVE',
  SET_PLAYER_OVERDRIVE_FLASH: 'SET_PLAYER_OVERDRIVE_FLASH',
  SET_ENEMY_OVERDRIVE_FLASH: 'SET_ENEMY_OVERDRIVE_FLASH',
  SET_SOUL_SHATTER: 'SET_SOUL_SHATTER',

  // === 타임라인 ===
  SET_TIMELINE_PROGRESS: 'SET_TIMELINE_PROGRESS',
  SET_TIMELINE_INDICATOR_VISIBLE: 'SET_TIMELINE_INDICATOR_VISIBLE',
  SET_EXECUTING_CARD_INDEX: 'SET_EXECUTING_CARD_INDEX',

  // === UI ===
  SET_IS_SIMPLIFIED: 'SET_IS_SIMPLIFIED',
  SET_SHOW_CHARACTER_SHEET: 'SET_SHOW_CHARACTER_SHEET',
  TOGGLE_CHARACTER_SHEET: 'TOGGLE_CHARACTER_SHEET',
  SET_SHOW_PTS_TOOLTIP: 'SET_SHOW_PTS_TOOLTIP',
  SET_SHOW_BAR_TOOLTIP: 'SET_SHOW_BAR_TOOLTIP',

  // === 상징 ===
  SET_ORDERED_RELICS: 'SET_ORDERED_RELICS',

  // === 전투 종료 ===
  SET_POST_COMBAT_OPTIONS: 'SET_POST_COMBAT_OPTIONS',

  // === 다음 턴 효과 ===
  SET_NEXT_TURN_EFFECTS: 'SET_NEXT_TURN_EFFECTS',
  UPDATE_NEXT_TURN_EFFECTS: 'UPDATE_NEXT_TURN_EFFECTS',

  // === 성찰 상태 ===
  SET_REFLECTION_STATE: 'SET_REFLECTION_STATE',

  // === 애니메이션 ===
  SET_PLAYER_HIT: 'SET_PLAYER_HIT',
  SET_ENEMY_HIT: 'SET_ENEMY_HIT',
  SET_PLAYER_BLOCK_ANIM: 'SET_PLAYER_BLOCK_ANIM',
  SET_ENEMY_BLOCK_ANIM: 'SET_ENEMY_BLOCK_ANIM',

  // === 자동진행 & 스냅샷 ===
  SET_AUTO_PROGRESS: 'SET_AUTO_PROGRESS',
  SET_RESOLVE_START_PLAYER: 'SET_RESOLVE_START_PLAYER',
  SET_RESOLVE_START_ENEMY: 'SET_RESOLVE_START_ENEMY',
  SET_RESPOND_SNAPSHOT: 'SET_RESPOND_SNAPSHOT',
  SET_REWIND_USED: 'SET_REWIND_USED',

  // === 상징 UI ===
  SET_HOVERED_RELIC: 'SET_HOVERED_RELIC',
  SET_RELIC_ACTIVATED: 'SET_RELIC_ACTIVATED',
  SET_ACTIVE_RELIC_SET: 'SET_ACTIVE_RELIC_SET',
  SET_MULTIPLIER_PULSE: 'SET_MULTIPLIER_PULSE',

  // === 전투 진행 ===
  SET_RESOLVED_PLAYER_CARDS: 'SET_RESOLVED_PLAYER_CARDS',

  // === 카드 툴팁 ===
  SET_HOVERED_CARD: 'SET_HOVERED_CARD',
  SET_TOOLTIP_VISIBLE: 'SET_TOOLTIP_VISIBLE',
  SET_PREVIEW_DAMAGE: 'SET_PREVIEW_DAMAGE',
  SET_PER_UNIT_PREVIEW_DAMAGE: 'SET_PER_UNIT_PREVIEW_DAMAGE',

  // === 통찰 시스템 ===
  SET_INSIGHT_BADGE: 'SET_INSIGHT_BADGE',
  SET_INSIGHT_ANIM_LEVEL: 'SET_INSIGHT_ANIM_LEVEL',
  SET_INSIGHT_ANIM_PULSE_KEY: 'SET_INSIGHT_ANIM_PULSE_KEY',
  SET_SHOW_INSIGHT_TOOLTIP: 'SET_SHOW_INSIGHT_TOOLTIP',

  // === 적 행동 툴팁 ===
  SET_HOVERED_ENEMY_ACTION: 'SET_HOVERED_ENEMY_ACTION',

  // === 카드 파괴 애니메이션 ===
  SET_DESTROYING_ENEMY_CARDS: 'SET_DESTROYING_ENEMY_CARDS',

  // === 카드 빙결 애니메이션 ===
  SET_FREEZING_ENEMY_CARDS: 'SET_FREEZING_ENEMY_CARDS',

  // === 빙결 순서 플래그 ===
  SET_FROZEN_ORDER: 'SET_FROZEN_ORDER',

  // === 피해 분배 시스템 ===
  SET_DISTRIBUTION_MODE: 'SET_DISTRIBUTION_MODE',
  SET_PENDING_DISTRIBUTION_CARD: 'SET_PENDING_DISTRIBUTION_CARD',
  SET_DAMAGE_DISTRIBUTION: 'SET_DAMAGE_DISTRIBUTION',
  UPDATE_DAMAGE_DISTRIBUTION: 'UPDATE_DAMAGE_DISTRIBUTION',
  SET_TOTAL_DISTRIBUTABLE_DAMAGE: 'SET_TOTAL_DISTRIBUTABLE_DAMAGE',
  RESET_DISTRIBUTION: 'RESET_DISTRIBUTION',

  // === 토큰 시스템 ===
  UPDATE_PLAYER_TOKENS: 'UPDATE_PLAYER_TOKENS',
  UPDATE_ENEMY_TOKENS: 'UPDATE_ENEMY_TOKENS',

  // === 복합 액션 ===
  RESET_TURN: 'RESET_TURN',
  RESET_ETHER_ANIMATION: 'RESET_ETHER_ANIMATION',
  RESET_BATTLE: 'RESET_BATTLE',
};
